(define (equal? item1 item2)
  (cond((and (not (pair? item1)) (not (pair? item2)))
        (eq? item1 item2))
       ((and (pair? item1) (pair? item2))
        (and (equal? (car item1) (car item2))
             (equal? (cdr item1) (cdr item2))))
       (else false)))