(define (square a b)
  (define (process-new-value)
    (if (has-value? b)
        (if (< (get-value b) 0)
            (error "square less than 0 -- SQUARE" (get-value b))
            (set-value! a (sqrt b) me))
        (if (has-value? a)
            (set-value! b (* (get-value a) (get-value a)) me)
            'ignore)))
  (define (process-forget-value)
    (forget-value! a me)
    (forget-value! b me)
    (process-new-value))
  (define (me require)
    (cond ((eq? require 'I-have-a-value)
           (process-new-value))
          ((eq? require 'I-lost-my-value)
           (process-forget-value))
          (else
           (error "Unknown requist -- SQUARE" require))))
  (connect a me)
  (connect b me)
  me)