(define (make-account balance password)
  (define times 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (if (eq? p password)
        (begin (set! times 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknow request -- MAKE ACCOUNT"
                                  m))))
        (begin (set! times (+ times 1))
               (if (>= times 7)
                   (error "Call the cops!")
                   (error "Incorrect password")))))
  dispatch)